name: 'Enable Red Hat entitled podman builds'
inputs:
  org:
    description: 'Red Hat account organization'
  activationkey:
    description: 'Red Hat account activation key'
  image:
    description: 'Container image to use to run subscription-manager register'
    default: 'registry.access.redhat.com/ubi8'
runs:
  using: 'composite'
  steps:
    - run: |
        NAME="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        NAME="${NAME#https://}"
        NAME="${NAME////-}"
        sudo mkdir -p /etc/pki/entitlement
        sudo chown $UID /etc/pki/entitlement
        podman run --name="$NAME" -v /etc/pki/entitlement:/etc/pki/entitlement-out:z --rm "${{ inputs.image }}" bash -c '/usr/sbin/subscription-manager register --org="${{ inputs.org }}" --activationkey="${{ inputs.activationkey }}" --name="'$NAME'" && cp /etc/pki/entitlement/* /etc/pki/entitlement-out/ && /usr/sbin/subscription-manager unregister'
      shell: bash
