name: Build RHEL container image
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/podman-entitlement
        with:
          org: ${{ secrets.redhat_org }}
          activationkey: ${{ secrets.redhat_activationkey }}
      - run: set -o pipefail ; podman run --rm registry.access.redhat.com/ubi9 dnf install -y zsh | tee podman-run.log
      - run: echo ${{ secrets.GITHUB_TOKEN }} | base64
      - uses: ./.github/actions/upload-artifact-encrypt
        with:
          name: podman-run.log
          path: podman-run.log
          secret: ${{ secrets.upload_secret }}
  check:
    name: Check the logs (that should have been encrypted)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ secrets.GITHUB_TOKEN }} | base64
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | base64
      - uses: ./.github/actions/download-artifact-decrypt
        with:
          name: podman-run.log
          secret: ${{ secrets.upload_secret }}
      - run: cat podman-run.log
