name: Build RHEL container image
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build container image
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        build-image: [ registry.access.redhat.com/ubi8, registry.access.redhat.com/ubi9, '' ]
        use-image: [ registry.access.redhat.com/ubi8, registry.access.redhat.com/ubi8-minimal, registry.access.redhat.com/ubi9, registry.access.redhat.com/ubi9-minimal ]
        podman: [ podman, docker ]
    env:
        DNF: dnf
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/podman-entitlement
        with:
          org: ${{ secrets.redhat_org }}
          activationkey: ${{ secrets.redhat_activationkey }}
          image: ${{ matrix.build-image }}
        if: matrix.build-image != ''
      - uses: ./.github/actions/podman-entitlement
        with:
          org: ${{ secrets.redhat_org }}
          activationkey: ${{ secrets.redhat_activationkey }}
        if: matrix.build-image == ''
      - run: echo "DNF=microdnf" >> $GITHUB_ENV
        if: endsWith( matrix.use-image, '-minimal')
      - run: set -o pipefail ; ${{ matrix.podman }} run --rm ${{ matrix.use-image }} $DNF install -y zsh | tee run.log
      - run: mkdir build ; ( echo "FROM ${{ matrix.use-image }}" ; echo "RUN $DNF install -y zsh" ) | tee build/Dockerfile
      - run: ${{ matrix.podman }} build build | tee build.log
      - uses: ./.github/actions/upload-artifact-encrypt
        with:
          name: run.log
          path: run.log
          secret: ${{ secrets.upload_secret }}
  check:
    name: Check the logs (that should have been encrypted)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/download-artifact-decrypt
        with:
          name: run.log
          secret: ${{ secrets.upload_secret }}
      - run: cat run.log
